apiVersion: v1
kind: Service
metadata:
  name: broker-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:AWS_REGION:AWS_ACCOUNT:certificate/AWS_CERTIFICATE"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "8883"
spec:
  type: LoadBalancer
  selector:
    app: broker
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts